apiVersion: v1
kind: Service
metadata:
  name: connector-service
  labels:
    name: connector-service
    app: splat
spec:
  type: NodePort
  selector:
    name: connector-pod
    app: splat
  ports:
  - port: 80